### PR TITLE
Team 6 - Add New Airport Popup

### PR DESCRIPTION
**Pull request by cornez89**
Clicking on the Add button of the Airports Page will now display a popup with entries, a calendar, and a rating selector to make adding an airport more intuitive. It's purely a decoration for now and we think we will get a Syncfusion liscense, so the annoying popup that asks for one is temporary.

### CODE REVIEW

**Comment by 4cadenr** [comment]
> Clicking on the Add button of the Airports Page will now display a popup with entries, a calendar, and a rating selector to make adding an airport more intuitive. It's purely a decoration for now.

We have to wait to be approved for a syncfusion community license to fix the extra pop-up, and they take a day or two to send it.

**Comment by rogersm-uwosh** [comment]
I would not rely on Syncfusion, as this is due by Tuesday (and I need time to review it). Just use the community toolkit described in class

**Comment by rogersm-uwosh** [comment]
Because of other PRs that have been approved, this now has conflicts that must be resolved. If you can please pull this, resolve the conflicts in an appropriate fashion and push the changes, I will be able to approve this.

**Comment by rogersm-uwosh** [comment]
I took a look at this page -- https://github.com/yurkinh/Plugin.Maui.Calendar. I thought you said you couldn't get any info out of it, but there are bindings for day, month and year, which should be sufficient for our needs.

**Comment by robbij25** [comment]
I resolved the merge conflict within the .csproj file.

**Comment by 4cadenr** [comment]
Ah this one isn't the one with that problem, I think I conflated the two. I remember spending an hour or two trying to get this one working at some point, but I don't remember exactly why I felt the need to stop using it.
________________________________

**Pull request merged**
